
package com.github.gabrielsilper.cliente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConsultaDadosServiceImplService", targetNamespace = "http://service.gabrielsilper.github.com/", wsdlLocation = "http://localhost:8080/servico/consultas?wsdl")
public class ConsultaDadosServiceImplService
    extends Service
{

    private final static URL CONSULTADADOSSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONSULTADADOSSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName CONSULTADADOSSERVICEIMPLSERVICE_QNAME = new QName("http://service.gabrielsilper.github.com/", "ConsultaDadosServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/servico/consultas?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTADADOSSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        CONSULTADADOSSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public ConsultaDadosServiceImplService() {
        super(__getWsdlLocation(), CONSULTADADOSSERVICEIMPLSERVICE_QNAME);
    }

    public ConsultaDadosServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTADADOSSERVICEIMPLSERVICE_QNAME, features);
    }

    public ConsultaDadosServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, CONSULTADADOSSERVICEIMPLSERVICE_QNAME);
    }

    public ConsultaDadosServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTADADOSSERVICEIMPLSERVICE_QNAME, features);
    }

    public ConsultaDadosServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaDadosServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IConsultaDadosService
     */
    @WebEndpoint(name = "ConsultaDadosServiceImplPort")
    public IConsultaDadosService getConsultaDadosServiceImplPort() {
        return super.getPort(new QName("http://service.gabrielsilper.github.com/", "ConsultaDadosServiceImplPort"), IConsultaDadosService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IConsultaDadosService
     */
    @WebEndpoint(name = "ConsultaDadosServiceImplPort")
    public IConsultaDadosService getConsultaDadosServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.gabrielsilper.github.com/", "ConsultaDadosServiceImplPort"), IConsultaDadosService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTADADOSSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw CONSULTADADOSSERVICEIMPLSERVICE_EXCEPTION;
        }
        return CONSULTADADOSSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
