
package com.github.gabrielsilper.cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IConsultaDadosService", targetNamespace = "http://service.gabrielsilper.github.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IConsultaDadosService {


    /**
     * 
     * @param uf
     * @param municipio
     * @return
     *     returns com.github.gabrielsilper.cliente.DadosPopulacaoDTO
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.gabrielsilper.github.com/IConsultaDadosService/getDadosPopulacaoRequest", output = "http://service.gabrielsilper.github.com/IConsultaDadosService/getDadosPopulacaoResponse")
    public DadosPopulacaoDTO getDadosPopulacao(
        @WebParam(name = "uf", partName = "uf")
        String uf,
        @WebParam(name = "municipio", partName = "municipio")
        String municipio);

    /**
     * 
     * @param uf
     * @param municipio
     * @return
     *     returns com.github.gabrielsilper.cliente.DadosSaudeDTO
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.gabrielsilper.github.com/IConsultaDadosService/getDadosSaudeRequest", output = "http://service.gabrielsilper.github.com/IConsultaDadosService/getDadosSaudeResponse")
    public DadosSaudeDTO getDadosSaude(
        @WebParam(name = "uf", partName = "uf")
        String uf,
        @WebParam(name = "municipio", partName = "municipio")
        String municipio);

    /**
     * 
     * @param cep
     * @return
     *     returns com.github.gabrielsilper.cliente.Cep
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.gabrielsilper.github.com/IConsultaDadosService/validarEnderecoCEPRequest", output = "http://service.gabrielsilper.github.com/IConsultaDadosService/validarEnderecoCEPResponse")
    public Cep validarEnderecoCEP(
        @WebParam(name = "cep", partName = "cep")
        String cep);

}
